package seo

// This file holds the markets the keyword tools accept. It was converted from
// the location table of OpenSEO (https://github.com/every-app/open-seo,
// src/shared/keyword-locations.ts) and is maintained by hand. The sources of
// truth are DataForSEO's /v3/dataforseo_labs/locations_and_languages endpoint
// (which countries DataForSEO Labs covers and the languages it serves for
// each) and /v3/serp/google/languages (the language codes DataForSEO accepts).

// location is one country a keyword request can target.
type location struct {
	code int
	name string
	// language is the default language: the one with the largest keyword
	// corpus in the country.
	language string
	// languages lists every language DataForSEO Labs serves for the country,
	// including the default. Nil means the default only.
	languages []string
	// adsOnly marks a country DataForSEO Labs does not cover. Its keyword data
	// comes from the Google Ads endpoints, which return no keyword difficulty
	// or search intent.
	adsOnly bool
}

// locations lists the countries OpenSEO offers for keyword data, sorted by name.
var locations = []location{
	{2008, "Albania", "sq", nil, false},
	{2012, "Algeria", "fr", []string{"ar", "fr"}, false},
	{2020, "Andorra", "ca", nil, true},
	{2024, "Angola", "pt", nil, false},
	{2032, "Argentina", "es", nil, false},
	{2051, "Armenia", "hy", nil, false},
	{2036, "Australia", "en", nil, false},
	{2040, "Austria", "de", nil, false},
	{2031, "Azerbaijan", "az", nil, false},
	{2044, "Bahamas", "en", nil, true},
	{2048, "Bahrain", "ar", nil, false},
	{2050, "Bangladesh", "bn", nil, false},
	{2052, "Barbados", "en", nil, true},
	{2056, "Belgium", "nl", []string{"de", "fr", "nl"}, false},
	{2084, "Belize", "en", nil, true},
	{2068, "Bolivia", "es", nil, false},
	{2070, "Bosnia and Herzegovina", "bs", nil, false},
	{2072, "Botswana", "en", nil, true},
	{2076, "Brazil", "pt", nil, false},
	{2096, "Brunei", "ms", nil, true},
	{2100, "Bulgaria", "bg", nil, false},
	{2854, "Burkina Faso", "fr", nil, false},
	{2116, "Cambodia", "en", nil, false},
	{2120, "Cameroon", "fr", nil, false},
	{2124, "Canada", "en", []string{"en", "fr"}, false},
	{2152, "Chile", "es", nil, false},
	{2170, "Colombia", "es", nil, false},
	{2188, "Costa Rica", "es", nil, false},
	{2384, "Cote d'Ivoire", "fr", nil, false},
	{2191, "Croatia", "hr", nil, false},
	{2196, "Cyprus", "el", []string{"el", "en"}, false},
	{2203, "Czechia", "cs", nil, false},
	{2208, "Denmark", "da", nil, false},
	{2214, "Dominican Republic", "es", nil, true},
	{2218, "Ecuador", "es", nil, false},
	{2818, "Egypt", "ar", []string{"ar", "en"}, false},
	{2222, "El Salvador", "es", nil, false},
	{2233, "Estonia", "et", nil, false},
	{2231, "Ethiopia", "en", nil, true},
	{2242, "Fiji", "en", nil, true},
	{2246, "Finland", "fi", nil, false},
	{2250, "France", "fr", nil, false},
	{2268, "Georgia", "en", nil, true},
	{2276, "Germany", "de", nil, false},
	{2288, "Ghana", "en", nil, false},
	{2300, "Greece", "el", []string{"el", "en"}, false},
	{2320, "Guatemala", "es", nil, false},
	{2831, "Guernsey", "en", nil, true},
	{2328, "Guyana", "en", nil, true},
	{2332, "Haiti", "fr", nil, true},
	{2340, "Honduras", "es", nil, true},
	{2344, "Hong Kong", "zh-TW", []string{"en", "zh-TW"}, false},
	{2348, "Hungary", "hu", nil, false},
	{2352, "Iceland", "is", nil, true},
	{2356, "India", "en", []string{"en", "hi"}, false},
	{2360, "Indonesia", "id", []string{"en", "id"}, false},
	{2368, "Iraq", "ar", nil, true},
	{2372, "Ireland", "en", nil, false},
	{2833, "Isle of Man", "en", nil, true},
	{2376, "Israel", "he", []string{"ar", "he"}, false},
	{2380, "Italy", "it", nil, false},
	{2388, "Jamaica", "en", nil, true},
	{2392, "Japan", "ja", nil, false},
	{2832, "Jersey", "en", nil, true},
	{2400, "Jordan", "ar", nil, false},
	{2398, "Kazakhstan", "ru", nil, false},
	{2404, "Kenya", "en", nil, false},
	{2414, "Kuwait", "ar", nil, true},
	{2417, "Kyrgyzstan", "ru", nil, true},
	{2418, "Laos", "en", nil, true},
	{2428, "Latvia", "lv", nil, false},
	{2422, "Lebanon", "ar", nil, true},
	{2438, "Liechtenstein", "de", nil, true},
	{2440, "Lithuania", "lt", nil, false},
	{2442, "Luxembourg", "fr", nil, true},
	{2450, "Madagascar", "fr", nil, true},
	{2454, "Malawi", "en", nil, true},
	{2458, "Malaysia", "en", []string{"en", "ms"}, false},
	{2462, "Maldives", "en", nil, true},
	{2470, "Malta", "en", nil, false},
	{2480, "Mauritius", "en", nil, true},
	{2484, "Mexico", "es", nil, false},
	{2498, "Moldova", "ro", nil, false},
	{2492, "Monaco", "fr", nil, false},
	{2496, "Mongolia", "en", nil, true},
	{2499, "Montenegro", "sr", nil, true},
	{2504, "Morocco", "ar", []string{"ar", "fr"}, false},
	{2508, "Mozambique", "pt", nil, true},
	{2104, "Myanmar (Burma)", "en", nil, false},
	{2516, "Namibia", "en", nil, true},
	{2524, "Nepal", "en", nil, true},
	{2528, "Netherlands", "nl", nil, false},
	{2554, "New Zealand", "en", nil, false},
	{2558, "Nicaragua", "es", nil, false},
	{2566, "Nigeria", "en", nil, false},
	{2807, "North Macedonia", "mk", nil, false},
	{2578, "Norway", "nb", nil, false},
	{2512, "Oman", "ar", nil, true},
	{2586, "Pakistan", "en", []string{"en", "ur"}, false},
	{2275, "Palestine", "ar", nil, true},
	{2591, "Panama", "es", nil, false},
	{2598, "Papua New Guinea", "en", nil, true},
	{2600, "Paraguay", "es", nil, false},
	{2604, "Peru", "es", nil, false},
	{2608, "Philippines", "en", []string{"en", "tl"}, false},
	{2616, "Poland", "pl", nil, false},
	{2620, "Portugal", "pt", nil, false},
	{2634, "Qatar", "ar", nil, true},
	{2642, "Romania", "ro", nil, false},
	{2646, "Rwanda", "en", nil, true},
	{2674, "San Marino", "it", nil, true},
	{2682, "Saudi Arabia", "ar", nil, false},
	{2686, "Senegal", "fr", nil, false},
	{2688, "Serbia", "sr", nil, false},
	{2702, "Singapore", "en", []string{"en", "zh-CN"}, false},
	{2703, "Slovakia", "sk", nil, false},
	{2705, "Slovenia", "sl", nil, false},
	{2710, "South Africa", "en", nil, false},
	{2410, "South Korea", "ko", nil, false},
	{2724, "Spain", "es", nil, false},
	{2144, "Sri Lanka", "en", nil, false},
	{2740, "Suriname", "nl", nil, true},
	{2752, "Sweden", "sv", nil, false},
	{2756, "Switzerland", "de", []string{"de", "fr", "it"}, false},
	{2158, "Taiwan", "zh-TW", nil, false},
	{2762, "Tajikistan", "ru", nil, true},
	{2834, "Tanzania", "en", nil, true},
	{2764, "Thailand", "th", nil, false},
	{2780, "Trinidad and Tobago", "en", nil, true},
	{2788, "Tunisia", "ar", nil, false},
	{2792, "Turkiye", "tr", nil, false},
	{2795, "Turkmenistan", "ru", nil, true},
	{2800, "Uganda", "en", nil, true},
	{2804, "Ukraine", "uk", []string{"ru", "uk"}, false},
	{2784, "United Arab Emirates", "en", []string{"ar", "en"}, false},
	{2826, "United Kingdom", "en", nil, false},
	{2840, "United States", "en", []string{"en", "es"}, false},
	{2858, "Uruguay", "es", nil, false},
	{2860, "Uzbekistan", "ru", nil, true},
	{2862, "Venezuela", "es", nil, false},
	{2704, "Vietnam", "vi", []string{"en", "vi"}, false},
	{2894, "Zambia", "en", nil, true},
	{2716, "Zimbabwe", "en", nil, true},
}

// supportedLanguages is the set of language codes the DataForSEO SERP API accepts.
var supportedLanguages = map[string]bool{
	"af": true, "ak": true, "sq": true, "am": true, "ar": true, "hy": true, "az": true,
	"ban": true, "eu": true, "be": true, "bn": true, "bs": true, "bg": true, "my": true,
	"ca": true, "ceb": true, "ny": true, "zh-CN": true, "zh-TW": true, "hr": true,
	"cs": true, "da": true, "nl": true, "en": true, "et": true, "ee": true, "fo": true,
	"fa": true, "fil": true, "fi": true, "fr": true, "fy": true, "gaa": true, "gl": true,
	"lg": true, "ka": true, "de": true, "el": true, "gu": true, "ht": true, "ha": true,
	"he": true, "hi": true, "hu": true, "is": true, "bem": true, "ig": true, "id": true,
	"ga": true, "it": true, "ja": true, "kn": true, "kk": true, "km": true, "rw": true,
	"rn": true, "kg": true, "ko": true, "mfe": true, "crs": true, "kri": true, "ckb": true,
	"ky": true, "lo": true, "lv": true, "ln": true, "lt": true, "ach": true, "mk": true,
	"mg": true, "ms": true, "ml": true, "mt": true, "mi": true, "mr": true, "mn": true,
	"ne": true, "nso": true, "nb": true, "nyn": true, "om": true, "ps": true, "pcm": true,
	"pl": true, "pt": true, "pt-BR": true, "pt-PT": true, "pa": true, "qu": true,
	"ro": true, "rm": true, "ru": true, "sr": true, "sr-Latn": true, "sr-ME": true,
	"st": true, "sn": true, "loz": true, "sd": true, "si": true, "sk": true, "sl": true,
	"so": true, "es": true, "es-419": true, "sw": true, "sv": true, "tl": true, "tg": true,
	"ta": true, "te": true, "th": true, "ti": true, "to": true, "lua": true, "tn": true,
	"tum": true, "tr": true, "tk": true, "uk": true, "ur": true, "uz": true, "vi": true,
	"cy": true, "wo": true, "xh": true, "yo": true, "zu": true,
}
